---
- name: "Linux: Health Check & Provisioning con Variables"
  hosts: os_linux
  become: yes
  
  # SECCIÓN DE VARIABLES: Aquí defines qué partición y qué límite quieres
  vars:
    new_username: "ecuador"

  tasks:
    - name: "Crear usuario '{{ new_username }}'"
      ansible.builtin.user:
        name: "{{ new_username }}"
        state: present
        shell: /bin/bash